OUTPUT_WINDOWS=./bin/Installer-Windows.exe
OUTPUT_LINUX=./bin/Installer-Linux
OWNER=bazelik-null
NAME=example
DEBUG=false
DISABLE_TERMINAL=

windows:
	@echo "Building project for Windows..."
	@cd BBQDeploy && \
	GOOS=windows go build \
		-ldflags="-s -w \
		$(DISABLE_TERMINAL) \
		-X 'main.repoOwner=$(OWNER)' \
		-X 'main.repoName=$(NAME)' \
		-X 'main.isDebug=$(DEBUG)'" \
		-o ../$(OUTPUT_WINDOWS) ./src/*.go

linux:
	@echo "Building project for Linux..."
	@cd BBQDeploy && \
	GOOS=linux go build \
		-ldflags="-s -w \
		-X 'main.repoOwner=$(OWNER)' \
		-X 'main.repoName=$(NAME)' \
        -X 'main.isDebug=$(DEBUG)'" \
		-o ../$(OUTPUT_LINUX) ./src/*.go

clean:
	@echo "Cleaning up..."
	@$(RM) $(OUTPUT_WINDOWS) $(OUTPUT_LINUX)

help:
	@echo "Use 'make windows' to build the Windows version."
	@echo "Use 'make linux' to build the Linux version."
	@echo "Use 'make clean' to clean up."

.PHONY: windows linux clean help

