OUTPUT_WINDOWS=./bin/Installer-Windows.exe
OUTPUT_LINUX=./bin/Installer-Linux
OWNER=bazelik-null
NAME=example

windows:
	@echo "Building project for Windows..."
	@GOOS=windows go build -ldflags="-s -w -H=windowsgui -X 'main.repoOwner=$(OWNER)' -X 'main.repoName=$(NAME)'" -o $(OUTPUT_WINDOWS) ./BBQDeploy/src/*.go

linux:
	@echo "Building project for Linux..."
	@GOOS=linux go build -ldflags="-s -w -X 'main.repoOwner=$(OWNER)' -X 'main.repoName=$(NAME)'" -o $(OUTPUT_LINUX) ./BBQDeploy/src/*.go

all:
	@echo "Building project for Windows..."
	@GOOS=windows go build -ldflags="-s -w -H=windowsgui -X 'main.repoOwner=$(OWNER)' -X 'main.repoName=$(NAME)'" -o $(OUTPUT_WINDOWS) ./BBQDeploy/src/*.go
	@echo "Building project for Linux..."
	@GOOS=linux go build -ldflags="-s -w -X 'main.repoOwner=$(OWNER)' -X 'main.repoName=$(NAME)'" -o $(OUTPUT_LINUX) ./BBQDeploy/src/*.go

clean:
	@echo "Cleaning up..."
	@$(RM) $(OUTPUT_WINDOWS) $(OUTPUT_LINUX)

help:
	@echo "Use 'make windows' to build the Windows version."
	@echo "Use 'make linux' to build the Linux version."
	@echo "Use 'make clean' to clean up."

.PHONY: all windows linux clean help
